# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-12 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='activated',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
