# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-14 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0004_auto_20170414_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
