# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-10 06:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contests', '0001_initial'),
        ('inout', '0005_auto_20170414_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='solved',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm', models.DateTimeField(auto_now_add=True)),
                ('time_taken', models.DecimalField(decimal_places=2, max_digits=5)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contests.Problem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
