# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inout', '0006_solved'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tobecon',
            field=models.BooleanField(default=False),
        ),
    ]
