# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 04:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20170610_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='contest_date',
        ),
        migrations.AddField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='contest',
            name='name',
            field=models.CharField(default=datetime.datetime(2017, 6, 11, 4, 40, 15, 87493, tzinfo=utc), max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
