# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-11 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20170611_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='contest',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
