# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-28 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20170611_0440'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='time_lim',
            field=models.FloatField(default=1.0),
        ),
    ]
